"""R10: experiments/gallery.html from every experiment: thumbnail, key metrics, links to the full renders."""
import glob, json, os
from PIL import Image
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXP = os.path.join(ROOT, "experiments")
rows = []
for d in sorted(glob.glob(os.path.join(EXP, "e*"))):
    try:
        p = json.load(open(f"{d}/params.json")); m = json.load(open(f"{d}/metrics.json"))
    except FileNotFoundError:
        continue
    name = os.path.basename(d)
    pics = [f for f in ("map.png", "countries.png", "cartogram.png") if os.path.exists(f"{d}/{f}")]
    if not pics:
        continue
    thumb = f"{d}/thumb.jpg"
    if not os.path.exists(thumb) or os.path.getmtime(thumb) < os.path.getmtime(f"{d}/{pics[0]}"):
        im = Image.open(f"{d}/{pics[0]}").convert("RGB"); im.thumbnail((640, 640)); im.save(thumb, quality=82)
    share = p.get("share") or round(1 / (1 + p["floor"]), 4)
    links = " ".join(f'<a href="{name}/{f}">{f[:-4]}</a>' for f in sorted(glob.glob(f"{d}/*.png")) for f in [os.path.basename(f)])
    rows.append(f"""<div class="card"><a href="{name}/{pics[0]}"><img src="{name}/thumb.jpg"></a>
<h3>{name}</h3><div class="meta">{p.get('method','diffusion')} | {p.get('grid','mercator')} {p['W']}x{p['H']} | share {share} | sigma {p.get('sigma_km', p.get('sigma',''))}</div>
<div class="metrics">density error p05/p95 <b>{m['log_ratio_popweighted_p05']:+.3f} / {m['log_ratio_popweighted_p95']:+.3f}</b> | anisotropy p50/p95 {m['anisotropy_popweighted_p50']:.1f} / {m['anisotropy_popweighted_p95']:.0f}
| folds {m.get('folds_before_repair', m['folds'])} -> {m['folds']} ({m.get('folds_in_populated_cells', '?')} populated) | twist p50 {m.get('twist_popweighted_p50_deg', float('nan')):.1f} deg | {m.get('seconds', 0):.0f} s</div>
<div class="links">{links}</div></div>""")
html = f"""<!doctype html><html><head><meta charset="utf-8"><title>historical-cartogram gallery</title>
<style>body{{font:13px/1.4 -apple-system,sans-serif;background:#111;color:#ddd;margin:20px}} .grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(420px,1fr));gap:18px}}
.card{{background:#1b1b1b;padding:10px;border-radius:6px}} img{{width:100%;display:block;border-radius:4px}} h3{{margin:8px 0 2px;font-size:14px}} .meta{{color:#9ab}} .links a{{color:#6cf;margin-right:6px}} b{{color:#fff}}</style></head>
<body><h1>historical-cartogram: gallery (X6)</h1><p>Generated by src/gallery.py. Metrics are population-weighted; density error is log(rho0 / area); twist is the local rotation angle (X8), zero for OT by construction.</p>
<div class="grid">{''.join(rows)}</div></body></html>"""
open(os.path.join(EXP, "gallery.html"), "w").write(html)
print(f"gallery: {len(rows)} cards")
