"""Regenerate experiments/INDEX.md from every experiment's params and metrics."""
import glob, json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rows = []
for d in sorted(glob.glob(os.path.join(ROOT, "experiments", "e*"))):
    try:
        p = json.load(open(f"{d}/params.json")); m = json.load(open(f"{d}/metrics.json"))
    except FileNotFoundError:
        continue
    sig = p.get("sigma_km", p.get("sigma", ""))
    rows.append(f"| {os.path.basename(d)} | {p.get('method','diffusion')} | {p.get('grid','mercator')} {p['W']}x{p['H']} | {p.get('x_boundary','wall')} | {p['floor']} | {sig} | {m['folds']} | {m.get('gate_folds','')} | {m['log_ratio_popweighted_p05']:+.2f} / {m['log_ratio_popweighted_p95']:+.2f} | {m['anisotropy_popweighted_p50']:.1f} / {m['anisotropy_popweighted_p95']:.0f} | {m['displacement_mean_px']:.0f} | {m['seconds']:.0f} |")
hdr = ("# Experiment index\n\nGenerated by `src/index.py`. log-ratio = population-weighted log(rho0/area), p05 / p95 (0 = perfect). "
       "Anisotropy p50 / p95. sigma: km for new runs, px for e001-e005. Gate = S4 (folds must be 0).\n\n"
       "| run | method | grid | x | floor | sigma | folds | gate | log-ratio p05/p95 | anisotropy | mean disp px | s |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n")
open(os.path.join(ROOT, "experiments", "INDEX.md"), "w").write(hdr + "\n".join(rows) + "\n")
print(f"{len(rows)} runs indexed")
