"""Keep the public repo small: writes experiments/.gitignore so that renders above a size limit stay local
(the gallery thumbnails, metrics, params and logs are always committed). Key experiments keep full renders
up to a larger limit. Run before committing experiments.
    python src/repo_hygiene.py [--limit-mb 2] [--key-limit-mb 15]"""
import os, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EX = os.path.join(ROOT, "experiments")
KEY = ("e033_", "e034_globe_equalarea_2048_share0.999", "L4_", "L6_", "geometry_", "timeline/L3_")
limit = float(sys.argv[sys.argv.index("--limit-mb") + 1]) if "--limit-mb" in sys.argv else 2.0
key_limit = float(sys.argv[sys.argv.index("--key-limit-mb") + 1]) if "--key-limit-mb" in sys.argv else 15.0
lines = ["# generated by src/repo_hygiene.py: big renders stay local; thumbs, metrics, params, logs are committed",
         "**/*.npz", "**/*.npy", "timeline/t_base_*/countries.png", "timeline/t_ghs_*/countries.png", "timeline/t_ssp2_*/countries.png", "**/*.tmp"]
local = 0.0
for r, _, fs in os.walk(EX):
    for f in sorted(fs):
        if not f.endswith(".png"): continue
        p = os.path.join(r, f); rel = os.path.relpath(p, EX); mb = os.path.getsize(p) / 1e6
        lim = key_limit if any(k in rel for k in KEY) else limit
        if mb > lim: lines.append(rel); local += mb
open(os.path.join(EX, ".gitignore"), "w").write("\n".join(lines) + "\n")
print(f"experiments/.gitignore: {len(lines) - 7} renders kept local ({local:.0f} MB); limit {limit} MB, key experiments {key_limit} MB")
